//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rmApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATION
    {
        public int ID_NOTIFICATION { get; set; }
        public string TABELREFERNSI { get; set; }
        public string TYPE { get; set; }
        public string TEXT { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
