//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rmApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJEK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROJEK()
        {
            this.FOTO = new HashSet<FOTO>();
            this.KOMENTAR = new HashSet<KOMENTAR>();
            this.PENCAIRANDANA = new HashSet<PENCAIRANDANA>();
            this.PROGRESPROJEK = new HashSet<PROGRESPROJEK>();
            this.RELATIONSHIP_12 = new HashSet<RELATIONSHIP_12>();
            this.SPONSOR = new HashSet<SPONSOR>();
            this.VIDEO = new HashSet<VIDEO>();
        }
    
        public int ID_PROYEK { get; set; }
        public int ID_PENGGUNA { get; set; }
        public int ID_KATEGORI { get; set; }
        public int ID_WILAYAH { get; set; }
        public string NAMA_PROYEK { get; set; }
        public string DESKRIPSI_SINGKAT { get; set; }
        public string DESKRIPSI_LENGKAP { get; set; }
        public string LINK { get; set; }
        public Nullable<bool> STATUS_PROYEK { get; set; }
        public Nullable<System.DateTime> TANGGAL_BERAKHIR { get; set; }
        public Nullable<decimal> TARGET_DANA { get; set; }
        public Nullable<bool> FITUR { get; set; }
        public Nullable<int> SUKA { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<decimal> KOMISI_FLAT { get; set; }
        public Nullable<decimal> KOMISI_PERSEN { get; set; }
        public Nullable<decimal> TOTAL_DANA { get; set; }
        public Nullable<decimal> SISA_DANA { get; set; }
        public string KETERANGAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOTO> FOTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KOMENTAR> KOMENTAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PENCAIRANDANA> PENCAIRANDANA { get; set; }
        public virtual PENGGUNA PENGGUNA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROGRESPROJEK> PROGRESPROJEK { get; set; }
        public virtual WILAYAH WILAYAH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELATIONSHIP_12> RELATIONSHIP_12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPONSOR> SPONSOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIDEO> VIDEO { get; set; }
    }
}
