//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rmApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class raihMimpiEntities1 : DbContext
    {
        public raihMimpiEntities1()
            : base("name=raihMimpiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FOTO> FOTO { get; set; }
        public virtual DbSet<KATEGORI> KATEGORI { get; set; }
        public virtual DbSet<KOMENTAR> KOMENTAR { get; set; }
        public virtual DbSet<LOGIN> LOGIN { get; set; }
        public virtual DbSet<PENCAIRANDANA> PENCAIRANDANA { get; set; }
        public virtual DbSet<PENGGUNA> PENGGUNA { get; set; }
        public virtual DbSet<PERAN> PERAN { get; set; }
        public virtual DbSet<PROGRESPROJEK> PROGRESPROJEK { get; set; }
        public virtual DbSet<PROJEK> PROJEK { get; set; }
        public virtual DbSet<RELATIONSHIP_12> RELATIONSHIP_12 { get; set; }
        public virtual DbSet<SPONSOR> SPONSOR { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<VIDEO> VIDEO { get; set; }
        public virtual DbSet<WILAYAH> WILAYAH { get; set; }
        public virtual DbSet<NOTIFICATION> NOTIFICATION { get; set; }
    }
}
