//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int Country_id { get; set; }
        public string Country1 { get; set; }
        public string Continent { get; set; }
        public int Region_id { get; set; }
        public Nullable<double> Surface_Area { get; set; }
        public Nullable<int> Indep_Year { get; set; }
        public Nullable<int> Population { get; set; }
        public Nullable<double> Life_Expectancy { get; set; }
        public Nullable<double> GNP { get; set; }
        public Nullable<double> GNPOld { get; set; }
        public string Local_Name { get; set; }
        public string Government_Form { get; set; }
        public string Head_Of_State { get; set; }
        public Nullable<int> Capital { get; set; }
        public string Code2 { get; set; }
    
        public virtual Region Region { get; set; }
    }
}
