//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.Country = new HashSet<Country>();
        }
    
        public int Region_id { get; set; }
        public string Region1 { get; set; }
    
        public virtual ICollection<Country> Country { get; set; }
    }
}
