//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rmApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOTO
    {
        public int ID_FOTO { get; set; }
        public int ID_PROYEK { get; set; }
        public Nullable<int> ID_PROGRES_PROYEK { get; set; }
        public string NAMA_FOTO { get; set; }
        public byte[] FOTO1 { get; set; }
        public Nullable<bool> UTAMA_PROYEK { get; set; }
        public Nullable<bool> UTAMA_PROGRES_PROYEK { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public string KETERANGAN { get; set; }
    
        public virtual PROGRESPROJEK PROGRESPROJEK { get; set; }
        public virtual PROJEK PROJEK { get; set; }
    }
}
