//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rmApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOMENTAR
    {
        public int ID_KOMENTAR { get; set; }
        public Nullable<int> ID_PENGGUNA { get; set; }
        public Nullable<int> ID_PROGRES_PROYEK { get; set; }
        public Nullable<int> ID_PROYEK { get; set; }
        public string ISI_KOMENTAR { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string KETERANGAN { get; set; }
    
        public virtual PENGGUNA PENGGUNA { get; set; }
        public virtual PROGRESPROJEK PROGRESPROJEK { get; set; }
        public virtual PROJEK PROJEK { get; set; }
    }
}
