//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rmApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class raihMimpiEntities : DbContext
    {
        public raihMimpiEntities()
            : base("name=raihMimpiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FOTO> FOTO { get; set; }
        public DbSet<KATEGORI> KATEGORI { get; set; }
        public DbSet<KOMENTAR> KOMENTAR { get; set; }
        public DbSet<LOGIN> LOGIN { get; set; }
        public DbSet<PENCAIRANDANA> PENCAIRANDANA { get; set; }
        public DbSet<PENGGUNA> PENGGUNA { get; set; }
        public DbSet<PERAN> PERAN { get; set; }
        public DbSet<PROGRESPROJEK> PROGRESPROJEK { get; set; }
        public DbSet<PROJEK> PROJEK { get; set; }
        public DbSet<RELATIONSHIP_12> RELATIONSHIP_12 { get; set; }
        public DbSet<SPONSOR> SPONSOR { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<VIDEO> VIDEO { get; set; }
        public DbSet<WILAYAH> WILAYAH { get; set; }
    }
}
