//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rmApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERAN
    {
        public PERAN()
        {
            this.LOGIN = new HashSet<LOGIN>();
        }
    
        public int ID_PERAN { get; set; }
        public string PERAN1 { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string KETERANGAN { get; set; }
    
        public virtual ICollection<LOGIN> LOGIN { get; set; }
    }
}
